spring:
  application:
    name: we
  profiles:
    include: secret
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P21D104?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P21D104
    password: 87TI2h7NjB
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size : 10MB
  output:
    ansi:
      enabled: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    defer-datasource-initialization: true
  mail:
    host: smtp.naver.com
    port: 465
    username: aaa@naver.com
    password: 12345

  data:
    redis:
      host: 3.36.87.173
      port: 6379
      password: BLUB7CLE2bjQ01I

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

audio-utils:
  upper-path: "audio/"

  
auth:
  use-dev-token: false

logging:
  level:
    com.akdong.we: debug

jwt:
  secret: ATRwjxphUEMEqYsPoah1I2wj8hszQp1sXYMXbZO0bRc1A5ksze1dG553AzkilHedExtraSecureKeyForHS512Algorithm
  access-token-expiration: 7200000
  refresh-token-expiration: 1209600000

cloud:
  aws:
    s3:
      bucket: insu-special-bucket
    credentials:
      accessKey1: AKIA274HQC5LIGEQ4GG4
      secretKey1: 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
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false

fin-api:
  url: https://finopenapi.ssafy.io/ssafy/api/v1
  apiKey: dfd5e9cc0d0d4cfd8d35e9ec2402f2dd
  managerId: rhkeh123@naver.com
  creationDate: 20240906
  expirationDate: 20250906

server:
  forward-headers-strategy : framework



