spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P21D104?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P21D104
    password: 87TI2h7NjB
    driver-class-name: org.mariadb.jdbc.Driver

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.naver.com
    port: 465
    username: aaa@naver.com
    password: 12345

  data:
    redis:
      port: 6379
      host: 3.36.87.173

logging:
  level:
    com.akdong.we: debug

jwt:
  secret: ATRwjxphUEMEqYsPoah1I2wj8hszQp1sXYMXbZO0bRc1A5ksze1dG553AzkilHedExtraSecureKeyForHS512Algorithm
  access-token-expiration: 7200000
  refresh-token-expiration: 1209600000

cloud:
  aws:
    s3:
      bucket: insu-special-bucket
    credentials:
      accessKey1: AKIA274HQC5LIGEQ4GG4
      secretKey1: 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
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false

fin-api:
  url: https://finopenapi.ssafy.io/ssafy/api/v1
  apiKey: dfd5e9cc0d0d4cfd8d35e9ec2402f2dd
  managerId: rhkeh123@naver.com
  creationDate: 20240906
  expirationDate: 20250906