spring:
  application:
    name: we
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    defer-datasource-initialization: true
  mail:
    host: smtp.naver.com
    port: 465
    protocol: smtps

  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

audio-utils:
  upper-path: "audio/"

  
auth:
  use-dev-token: false

---
## local
spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml

  data:
    redis:
      host: localhost
      port: 6379

fast-api:
  url: http://192.168.100.149:8000
