pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                script{
                dir('we-springboot') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                    sh 'chmod +x ./docker_install.sh'
                    sh './docker_install.sh'
                    }
                }
            }
        }
        stage('Deploy'){
            steps{
                script{
                    sh 'docker build -f we-springboot/Dockerfile -t jenkins-signal .'
                    sh 'docker rm -f jenkins-signal'
                    sh 'docker run -d --name jenkins-signal -p 8080:8080 jenkins-signal'
                }
            }
        }
    }
}
